[mcp_servers.supabase]
url = "https://mcp.supabase.com/mcp?project_ref=seanzbqtziullcmfwamn"
bearer_token = "sbp_2092db213a156aa17c8815e090de1d8cde653496"

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp", "--api-key", "ctx7sk-f76ca78f-e71f-4a60-98b8-9e55c621dbe7"]

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest"]

[mcp_servers.livekit-docs]
url = "https://docs.livekit.io/mcp"